#AndroidIDE: enforce UTF-8 & locale for Gradle daemon
#Thu Nov 20 01:28:46 GMT 2025
org.gradle.caching=true
android.nonTransitiveRClass=false
systemProp.user.language=en
systemProp.user.country=US
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.jvmargs=-Xmx4096M -Dkotlin.daemon.jvm.options\="-Xmx4096M" -XX\:+HeapDumpOnOutOfMemoryError --add-opens java.base/java.lang\=ALL-UNNAMED --add-opens java.base/java.util\=ALL-UNNAMED --add-opens java.base/java.io\=ALL-UNNAMED -Dfile.encoding\=UTF-8 -Dsun.jnu.encoding\=UTF-8 -Duser.language\=en -Duser.country\=US
android.useAndroidX=true
android.enableJetifier=false
android.jetifier.ignorelist=common-30.2.2.jar
systemProp.https.protocols=TLSv1,TLSv1.1,TLSv1.2
systemProp.sun.jnu.encoding=UTF-8
ndk.dir=/data/user/0/com.tom.rv2ide/files/home/android-sdk/ndk/29.0.14033849
systemProp.file.encoding=UTF-8
android.aapt2FromMavenOverride=/data/data/com.tom.rv2ide/files/home/android-sdk/build-tools/35.0.1/aapt2
cmake.dir=/data/data/com.tom.rv2ide/files/usr
